Allow using PPXes as libraries
melange-re/melange pull request #171
Opened 2021-04-11 01:23 UTC by anmonteiro

fixes #121 

- generates a ppxlib driver on the fly

#### TODO:

- [ ] allow passing arguments to the ppx

2021-04-11 09:38 UTC, EduardoRFS requested changes
Two small nits

2021-04-11 09:38 UTC, EduardoRFS commented on jscomp/bsb/bsb_merlin_gen.ml
> +      Buffer.add_string buffer ".melange.eobjs/ppx.exe"
**warning** hard coded string

2021-04-11 09:38 UTC, EduardoRFS commented on jscomp/bsb/bsb_ninja_gen.ml
>      (* emitted in bsb_main *)
So this comment is now invalid?
```suggestion
```

2021-04-11 21:52 UTC, merged

2021-04-22 20:35 UTC, TheSpyder commented
How do I make use of this? It's not really clear from looking at the changes.

2021-04-22 21:12 UTC, anmonteiro commented
@TheSpyder this will definitely need documented, and we've added it to the list in #105.

A few informal notes:

1. depend on the PPXes you want via esy (or OPAM or Nix, anything that knows how to install PPXes with the ocamlfind toolchain)
2. add them to `ppx-flags` as usual, with just the ppx name (this is the important part -- it should match whatever the findlib name is. Generally it's also the package name)
3. Profit!

2021-04-22 23:59 UTC, TheSpyder commented
That's the part I'm not clear on, the findlib name. I'm trying to make a branch of my old favourite [decco](https://github.com/reasonml-labs/decco) that can integrate with this feature, to measure the speed difference on my fairly large project.

2021-04-23 00:00 UTC, anmonteiro commented
you can run `esy ls-libs` I believe, which will tell you the name of the library.

2021-04-23 00:01 UTC, anmonteiro commented
You need to depend on decco from source, btw, in your case via esy. I don't know how easy this is, but we could make a PR.

2021-04-23 00:11 UTC, TheSpyder commented
yes, I tried that and it still tried to execute it as a binary instead of loading it as a library. I just need to fiddle a bit more (I'm currently trying to lift the `esy` project up to the respository root instead of having it in a subfolder, to see if that helps).

2021-04-23 01:11 UTC, TheSpyder commented
I can't get it working, [here's the branch I tried](https://github.com/thespyder/decco/tree/melange), but I also realised that this "PPX as library" feature really only helps if there are multiple PPX. It still builds the ppx as a separate executable, so for single ppx use it won't be any faster than the precompiled binary (just easier to install since precompiled executables are not required).

This feature will likely help me in the future, but it's no longer important for me to try and get it working today :)

2021-04-23 15:27 UTC, EduardoRFS commented
@TheSpyder yeah that's true for us, but there is always multiple ppx pass, because we do a ppx pass ourselves.

Ideally we should move Melange PPX to ppxlib